networks:
  olkkani_network:
    external: true

services:
  blue:
    container_name: lfr-frontend
    image: ${IMAGE_NAME:-ghcr.io/olkkani/lostark-for-rice-front:latest}
    ports:
      - "3000:3000"
    networks:
      - olkkani_network
    environment:
      - TZ=Asia/Seoul
    restart: always

  green:
    container_name: lfr-f-green
    image: ${IMAGE_NAME:-ghcr.io/olkkani/lostark-for-rice-front:latest}
    ports:
      - "3001:3000"
    networks:
      - olkkani_network
    environment:
      - TZ=Asia/Seoul
    restart: always

  nginx:
    image: macbre/nginx-http3:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - olkkani_network
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /home/ec2-user/lfr/nginx/frontend.conf:/etc/nginx/conf.d/frontend.conf
      - /home/ec2-user/lfr/nginx/backend.conf:/etc/nginx/conf.d/backend.conf
      - /home/ec2-user/lfr/nginx/front-actvie-upstream.conf:/etc/nginx/front-actvie-upstream.conf
      - /home/ec2-user/lfr/nginx/back-active-upstream.conf:/etc/nginx/back-active-upstream.conf
      - /home/ec2-user/lfr/certs:/etc/letsencrypt
      - /home/ec2-user/lfr/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/ec2-user/lfr/certs:/etc/letsencrypt
      - /home/ec2-user/lfr/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
