networks:
  olkkani_network:
    external: true

services:
  blue:
    container_name: lfr-f-blue
    image: ${IMAGE_NAME:-ghcr.io/olkkani/lostark-for-rice-front:latest}
    ports:
      - "3000:3000"
    networks:
      - olkkani_network
    environment:
      - TZ=Asia/Seoul
    restart: always

  green:
    container_name: lfr-f-green
    image: ${IMAGE_NAME:-ghcr.io/olkkani/lostark-for-rice-front:latest}
    ports:
      - "3001:3000"
    networks:
      - olkkani_network
    environment:
      - TZ=Asia/Seoul
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - olkkani_network
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /home/ec2-user/lfr-f/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./build:/usr/share/nginx/html
    restart: always
